apiVersion: v2
name: authmanager
description: A Helm chart for MOSIP Authentication Manager module
type: application
version: 0.0.1-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - auth
  - authmanager
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
